name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WorldEditSelectionVisualizer
          path: plugin/build/libs/WorldEditSelectionVisualizer-*.jar
          overwrite: true
